apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9617'
spec:
  selector: 
    app: pihole-exporter
  type: ClusterIP  
  ports:
    - port: 9617
      targetPort: 9617
