apiVersion: v1
kind: Service
metadata:
  name: unify-poller-service
  namespace: unify-poller
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9130'
spec:
  selector: 
    app: unify-poller
  type: ClusterIP  
  ports:
    - port: 37288
      targetPort: 37288
