apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
    vol: prom-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
