apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter-service
  namespace: monitoring
spec:
  selector: 
    app: snmp-exporter
  type: ClusterIP  
  ports:
    - port: 9116
      targetPort: 9116
