---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: database
    app.kubernetes.io/version: v10.1
    app.kubernetes.io/type: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: database
        app.kubernetes.io/version: v10.1
        app.kubernetes.io/type: postgres
    spec:
      initContainers:
        - name: fix-permissions
          image: postgres:10.1
          command: ["sh", "-c", "chown -R postgres:postgres /var/lib/postgresql"]
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: nextcloud-storage-postgres
      containers:
        - name: postgres
          image: postgres:10.1
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/db-files/
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_USER
              value: nextcloud
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: nextcloud-storage-postgres
      volumes:
        - name: nextcloud-storage-postgres
          persistentVolumeClaim:
            claimName: nextcloud-storage-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-data-pvc
  namespace: nextcloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
    vol: nextcloud-storage-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db-service
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: database
    app.kubernetes.io/version: v10.1
    app.kubernetes.io/type: postgres
spec:
  selector: 
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: database
  type: ClusterIP  
  ports:
    - port: 5432
      targetPort: 5432
