apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pvc-lh
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    vol: grafana-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
