kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
    receivers:
    - name: slack
      slack_configs:
      # Alertmanager doesnt allow to overwrite this using env variables, therefore it has to
      # hardcoded in plain, thanks alermanager team!!
      - api_url: 'here yor api url'
        channel: '#alerts'
